worker/build.sbt
worker/src/main/resources/quartz.properties
worker/src/main/scala/com/lucidchart/piezo/Worker.scala
worker/src/test/scala/com/lucidchart/piezo/WorkerTest.scala

Writes the heartbeat timestamp to a configurable file. @bravefoot will you please review this?

report worker run loop heartbeat in configurable file

---

admin/app/com/lucidchart/piezo/admin/controllers/HealthCheck.scala
admin/app/com/lucidchart/piezo/admin/controllers/HealthCheckController.scala
admin/conf/application.conf
admin/conf/routes
admin/test/com/lucidchart/piezo/admin/controllers/HealthCheck.scala

Create Healthcheck endpoint that checks workers health

---

.travis.yml
admin/app/Global.scala
admin/app/com/lucidchart/piezo/admin/RequestStatCollector.scala
admin/project/Build.scala
admin/project/build.properties
admin/project/plugins.sbt
admin/test/IntegrationSpec.scala
admin/test/com/lucidchart/piezo/admin/controllers/JobsControllerTest.scala
admin/test/com/lucidchart/piezo/admin/controllers/JobsService.scala
admin/test/com/lucidchart/piezo/admin/controllers/TriggersService.scala
admin/test/com/lucidchart/piezo/admin/util/DummyClassGeneratorTest.scala
worker/build.sbt
worker/src/main/scala/com/lucidchart/piezo/GeneratorClassLoader.scala
worker/src/main/scala/com/lucidchart/piezo/jobs/monitoring/HeartBeat.scala
worker/src/main/scala/com/lucidchart/piezo/util/DummyClassGenerator.scala

I did this during the retreat but never polished it off until now. @bravefoot will you review this for me?

Play 2.3 migration

---

admin/build/createpackage
admin/makefile
admin/project/Build.scala

@pauldraper will you please review this?

update packaging scripts to work with new play/sbt versions

---

admin/app/com/lucidchart/piezo/admin/controllers/Jobs.scala
admin/app/com/lucidchart/piezo/admin/controllers/Triggers.scala
admin/app/com/lucidchart/piezo/admin/views/job.scala.html
admin/conf/routes

Feel free to critique the new endpoint url @disaacson

provide a way for someone to run a job immediately

---

admin/app/com/lucidchart/piezo/admin/controllers/Jobs.scala
admin/app/com/lucidchart/piezo/admin/utils/JobUtils.scala
admin/public/js/jobData.js

fixes for job data map with multiple values, when adding and editing jobs

---

admin/app/com/lucidchart/piezo/admin/controllers/Jobs.scala
admin/app/com/lucidchart/piezo/admin/controllers/TriggerHelper.scala
admin/app/com/lucidchart/piezo/admin/controllers/Triggers.scala
admin/app/com/lucidchart/piezo/admin/views/job.scala.html
admin/app/com/lucidchart/piezo/admin/views/jobs.scala.html
admin/project/Build.scala
admin/public/stylesheets/main.css
worker/build.sbt
worker/src/main/scala/com/lucidchart/piezo/TriggerHistoryModel.scala

Also, the Jobs History table now sorts by start time and job names are links on the Jobs page.

Added table for untriggered jobs

---

admin/app/com/lucidchart/piezo/admin/controllers/Triggers.scala
admin/app/com/lucidchart/piezo/admin/views/jobs.scala.html
admin/app/com/lucidchart/piezo/admin/views/triggers.scala.html

Each trigger is displayed once with next two fire times. Table sorts by next fire time and then by priority if fire times are the same.

Added Upcoming Triggers table to Triggers page

---

worker/src/main/scala/com/lucidchart/piezo/TriggerHistoryModel.scala

@marwtki would you mind reviewing this ASAP? We are getting errors in production about trying to add triggers to the history table.
Thanks!

Fix exceptions adding triggers to history table

---

worker/src/main/scala/com/lucidchart/piezo/Worker.scala

We use upstart to manager our quartz jobs. Upstart sends SIGTERM to
stop the upstart job. Without this change, this terminates the jobs
without calling scheduler.shutdown(true). I think this will fix the
issues we have of triggers being set to run in the past. If not, it's
still a more clean shutdown of quartz.

Guarantees that scheduler gets shut down on SIGTERM

---

admin/app/com/lucidchart/piezo/admin/controllers/Jobs.scala
admin/app/com/lucidchart/piezo/admin/controllers/Triggers.scala
admin/app/com/lucidchart/piezo/admin/views/job.scala.html
admin/app/com/lucidchart/piezo/admin/views/trigger.scala.html
admin/conf/routes

You can now pause and resume a trigger from the UI. The pause/resume button will only show up for a job if there are one or more cron triggers for that job.

Add pause and resume button for triggers and jobs

---

.travis.yml
build.sbt
worker/build.sbt

This change, allows us to publish, piezo worker for both scala 2-11 and scala-12

publish piezo-worker in scala 2-12 and 2-11

---

.travis.yml

add a working deploy api key for lucidsoftware account

---

admin/app/com/lucidchart/piezo/admin/views/job.scala.html

On clicking the pause icon, a div appears with a prompt that says "Are you sure you want to pause the job?" and two buttons (Pause and Cancel). Only on clicking the Pause button does the job pause. This behavior is similar to what happens when we try to delete a job.

PROD-1579 Added confirmation step for pausing Piezo jobs.

---

admin/app/com/lucidchart/piezo/admin/views/job.scala.html
admin/conf/application.conf

What the pause dialog looks like in production after my changes:

PROD-1577 Make pause dialog red and bold in production environments

---

.travis.yml
README.md
build.sbt

Upload artifacts to the "piezo" distribution instead of to "trusty", "xenial", and "bionic". Also just always use systemd, because trusty is really old now.

Apt distro

---

admin/app/com/lucidchart/piezo/GeneratorClassLoader.scala

When updating the scala version, I inadvertently broke the classloader that GeneratorClassLoader used.

Classloader fix

---

admin/app/com/lucidchart/piezo/admin/controllers/HealthCheck.scala

After checking workers the heartbeat file is now closed by the admin.

Fixed file leaking. Heartbeat file is now closed by admin after being used

---

.github/workflows/ci.yml

Because I couldn't get it to work, and I think the account is gone now.

Don't publish deb to jfrog artifactory

---

admin/app/com/lucidchart/piezo/admin/controllers/TriggerHelper.scala
admin/app/com/lucidchart/piezo/admin/controllers/Triggers.scala
admin/app/com/lucidchart/piezo/admin/views/editTrigger.scala.html
worker/src/main/scala/com/lucidchart/piezo/TriggerMonitoringModel.scala

Any existing medium priorities will be interpreted as Low going forward

PROD-2562 Get rid of Medium monitoring priority

---

.github/workflows/ci.yml

See: https://github.com/actions/runner-images/issues/8362

chore: Replace hub with gh
